config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'home#profile'
  patch 'upload_avatar', to: 'users#upload_avatar'
  delete 'delete_avatar', to: 'users#delete_avatar'
  resources :doctors, only: %i[index show] do
    resources :appointments, only: %i[new create]
  end
  resources :appointments, only: %i[index new create] do
    resource :recommendation, only: %i[new create]
  end

  resources :recommendations, only: %i[show]
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!

  def profile
    @doctors = User.doctors
    @categories = Category.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
    <div class="container-fluid">
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= image_tag 'logo.jpg', width: '40px' %>
          </li>
        </ul>
        <% if user_signed_in? %>
          <div class="d-flex gap-2">
            <%= link_to 'Profile', root_path, class: "btn btn-outline-primary" %>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/home/profile.html.erb
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-8 col-md-6 col-lg-4">
      <div class="card shadow-sm p-4 bg-light text-center">

        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar.variant(resize_to_limit: [140, 140]),
                        width: 140, height: 140,
                        class: "rounded-circle mx-auto d-block mb-3" %>
        <% else %>
          <%= image_tag "default-avatar.png",
                        width: 140, height: 140,
                        class: "rounded-circle mx-auto d-block mb-3" %>
        <% end %>

        <h5 class="mb-0"><%= current_user.first_name %> <%= current_user.last_name %></h5>
        <p  class="text-muted mb-3"><%= current_user.phone %></p>

        <% if current_user.avatar.attached? %>
          <%= button_to "Delete photo",
                        delete_avatar_path,
                        method: :delete,
                        class: "btn btn-outline-danger btn-sm w-100 mb-3" %>
        <% else %>
          <%= form_with model: current_user,
                        url: upload_avatar_path,
                        method: :patch,
                        local: true,
                        html: { multipart: true } do |f| %>

            <div class="mb-2">
              <%= f.file_field :avatar, class: "form-control form-control-sm" %>
            </div>
            <%= f.submit "Upload photo", class: "btn btn-primary btn-sm w-100 mb-3" %>
          <% end %>
        <% end %>
        <% if current_user.doctor? %>
          <div class="d-grid gap-2">
            <%= link_to "Appointments", appointments_path, class: "btn btn-outline-primary" %>
          </div>
        <% else %>
          <div class="d-grid gap-2">
            <%= link_to "Doctors", doctors_path, class: "btn btn-outline-primary" %>
            <%= link_to "Appointments", appointments_path, class: "btn btn-outline-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>